const carsData = [
	{
		id: 0,
		carName: "fiat",
		priceCategory: "basic",
		location: "Rzeszów",
		costPerDay: 100,
		avgConsumption: 5,
		carsAvailable: 3,
	},
	{
		id: 1,
		carName: "audi",
		priceCategory: "standard",
		location: "Kraków",
		costPerDay: 150,
		avgConsumption: 6,
		carsAvailable: 2,
	},
	{
		id: 2,
		carName: "porsche",
		priceCategory: "medium",
		location: "Wrocław",
		costPerDay: 200,
		avgConsumption: 8,
		carsAvailable: 5,
	},
	{
		id: 3,
		carName: "lamborghini",
		priceCategory: "premium",
		location: "Szczecin",
		costPerDay: 300,
		avgConsumption: 10,
		carsAvailable: 8,
	},
	{
		id: 4,
		carName: "nissan",
		priceCategory: "basic",
		location: "Rzeszów",
		costPerDay: 100,
		avgConsumption: 5,
		carsAvailable: 13,
	},
	{
		id: 5,
		carName: "volvo",
		priceCategory: "standard",
		location: "Kraków",
		costPerDay: 150,
		avgConsumption: 6.5,
		carsAvailable: 6,
	},
	{
		id: 6,
		carName: "seat",
		priceCategory: "medium",
		location: "Kraków",
		costPerDay: 200,
		avgConsumption: 8.5,
		carsAvailable: 4,
	},
	{
		id: 7,
		carName: "ferrari",
		priceCategory: "premium",
		location: "Poznań",
		costPerDay: 300,
		avgConsumption: 15,
		carsAvailable: 10,
	},
];
export default carsData;
